[projects."/home/caphe/Documents/bb/ezviz"]
trust_level = "trusted"

[projects."/home/caphe/Documents/res/saml"]
trust_level = "trusted"

[projects."/home/caphe/Documents/bb/doppler"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4

[features]
goals = true
