preload = ~/.config/hypr/images/backiee-325856-landscape.jpg

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/images/backiee-325856-landscape.jpg
}

wallpaper {
    monitor = HDMI-A-2
    path = ~/.config/hypr/images/backiee-325856-landscape.jpg
}

splash = false
