console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blacks.segments]]
    type='path'
    style='plain'
    background = 'transparent'
    foreground = ''
